export type DiPopoverPlacement
  = | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'left'
    | 'left-start'
    | 'left-end'
    | 'right'
    | 'right-start'
    | 'right-end'

export type DiPopoverSize = 'sm' | 'md' | 'lg'
export type DiPopoverWidth = 'auto' | 'trigger' | 'full'
