import type { MenuItem } from '@/shared/types/models'

export const menuItems: MenuItem[] = [
  { type: 'label', id: 'main-label', label: 'menu.groups.main' },
  {
    id: 'dashboards',
    label: 'menu.dashboard',
    icon: 'homeOutlineRounded',
    children: [
      { id: 'crm', label: 'menu.crm', route: '/dashboards/crm' },
      { id: 'ecommerce', label: 'menu.ecommerce', route: '/dashboards/ecommerce' },
      { id: 'analytics', label: 'menu.analytics', route: '/dashboards/analytics' },
      { id: 'courses', label: 'menu.courses', route: '/dashboards/courses' },
      { id: 'crypto', label: 'menu.crypto', route: '/dashboards/crypto' },
      { id: 'hrm', label: 'menu.hrm', route: '/dashboards/hrm' },
      { id: 'jobs', label: 'menu.jobs', route: '/dashboards/jobs' },
      { id: 'nft', label: 'menu.nft', route: '/dashboards/nft' },
      { id: 'personal', label: 'menu.personal', route: '/dashboards/personal' },
      { id: 'projects', label: 'menu.projects', route: '/dashboards/projects' },
      { id: 'sales', label: 'menu.sales', route: '/dashboards/sales' },
      { id: 'stocks', label: 'menu.stocks', route: '/dashboards/stocks' },
    ],
  },
  { type: 'label', id: 'components-label', label: 'menu.groups.components' },
  {
    id: 'ui-elements',
    label: 'menu.uiElements',
    icon: 'componentDropdown',
    children: [
      { id: 'alerts', label: 'menu.alerts', route: '/ui-elements/alerts' },
      { id: 'badge', label: 'menu.badge', route: '/ui-elements/badge' },
      { id: 'breadcrumb', label: 'menu.breadcrumb', route: '/ui-elements/breadcrumb' },
      { id: 'buttons', label: 'menu.buttons', route: '/ui-elements/buttons' },
      { id: 'icons', label: 'menu.icons', route: '/ui-elements/icons' },
      { id: 'loadings', label: 'menu.loadings', route: '/ui-elements/loadings' },
      { id: 'logo-loading', label: 'menu.logoLoading', route: '/ui-elements/logo-loading' },
      { id: 'button-group', label: 'menu.buttonGroup', route: '/ui-elements/button-group' },
      { id: 'cards', label: 'menu.cards', route: '/ui-elements/cards' },
      { id: 'dropdowns', label: 'menu.dropdowns', route: '/ui-elements/dropdowns' },
      { id: 'images-figures', label: 'menu.imagesFigures', route: '/ui-elements/images-figures' },
      {
        id: 'links-interactions',
        label: 'menu.linksInteractions',
        route: '/ui-elements/links-interactions',
      },
      { id: 'list-group', label: 'menu.listGroup', route: '/ui-elements/list-group' },
      { id: 'navs-tabs', label: 'menu.navsTabs', route: '/ui-elements/navs-tabs' },
      { id: 'object-fit', label: 'menu.objectFit', route: '/ui-elements/object-fit' },
      { id: 'pagination', label: 'menu.pagination', route: '/ui-elements/pagination' },
      { id: 'popovers', label: 'menu.popovers', route: '/ui-elements/popovers' },
      { id: 'progress', label: 'menu.progress', route: '/ui-elements/progress' },
      { id: 'switch', label: 'menu.switch', route: '/ui-elements/switch' },
      { id: 'toasts', label: 'menu.toasts', route: '/ui-elements/toasts' },
      { id: 'tooltips', label: 'menu.tooltips', route: '/ui-elements/tooltips' },
      { id: 'typography', label: 'menu.typography', route: '/ui-elements/typography' },
    ],
  },
  {
    id: 'forms',
    label: 'menu.forms',
    icon: 'form48regular',
    children: [
      {
        id: 'form-elements',
        label: 'menu.formElements',
        children: [
          { id: 'inputs', label: 'menu.inputs', route: '/forms/form-elements/inputs' },
          { id: 'range', label: 'menu.range', route: '/forms/form-elements/range' },
          {
            id: 'range-slider',
            label: 'menu.rangeSlider',
            route: '/forms/form-elements/range-slider',
          },
          { id: 'select', label: 'menu.select', route: '/forms/form-elements/select' },
        ],
      },
    ],
  },
  {
    id: 'advanced-ui',
    label: 'menu.advancedUi',
    icon: 'party',
    children: [
      { id: 'accordion', label: 'menu.accordion', route: '/advanced-ui/accordion' },
      { id: 'collapse', label: 'menu.collapse', route: '/advanced-ui/collapse' },
      { id: 'carousel', label: 'menu.carousel', route: '/advanced-ui/carousel' },
      { id: 'modals', label: 'menu.modals', route: '/advanced-ui/modals' },
      { id: 'drawer', label: 'menu.drawer', route: '/advanced-ui/drawer' },
      { id: 'navbar', label: 'menu.navbar', route: '/advanced-ui/navbar' },
      { id: 'skeleton', label: 'menu.skeleton', route: '/advanced-ui/skeleton' },
      { id: 'rating', label: 'menu.rating', route: '/advanced-ui/rating' },
    ],
  },
  { type: 'label', id: 'system-label', label: 'menu.groups.system' },
  {
    id: 'error',
    label: 'menu.error',
    icon: 'exclamationTriangle',
    children: [
      { id: 'error-401', label: 'menu.error401', route: '/error/401' },
      { id: 'error-404', label: 'menu.error404', route: '/error/404' },
      { id: 'error-500', label: 'menu.error500', route: '/error/500' },
    ],
  },
  {
    id: 'utility',
    label: 'menu.utility',
    icon: 'medalLine',
    children: [
      { id: 'avatar', label: 'menu.avatar', route: '/utility/avatar' },
      { id: 'colors', label: 'menu.colors', route: '/utility/colors' },
    ],
  },
]
