import type { MenuItem } from '@/shared/types/models'

export const menuItems: MenuItem[] = [
  { type: 'label', id: 'main-label', label: 'menu.groups.main' },
  {
    id: 'dashboards',
    label: 'menu.dashboard',
    icon: 'homeOutlineRounded',
    children: [
      { id: 'crm', label: 'menu.crm', route: '/dashboards/crm' },
      { id: 'ecommerce', label: 'menu.ecommerce', route: '/dashboards/ecommerce' },
      { id: 'analytics', label: 'menu.analytics', route: '/dashboards/analytics' },
      { id: 'courses', label: 'menu.courses', route: '/dashboards/courses' },
      { id: 'crypto', label: 'menu.crypto', route: '/dashboards/crypto' },
      { id: 'hrm', label: 'menu.hrm', route: '/dashboards/hrm' },
      { id: 'jobs', label: 'menu.jobs', route: '/dashboards/jobs' },
      { id: 'nft', label: 'menu.nft', route: '/dashboards/nft' },
      { id: 'personal', label: 'menu.personal', route: '/dashboards/personal' },
      { id: 'projects', label: 'menu.projects', route: '/dashboards/projects' },
      { id: 'sales', label: 'menu.sales', route: '/dashboards/sales' },
      { id: 'stocks', label: 'menu.stocks', route: '/dashboards/stocks' },
    ],
  },
  { type: 'label', id: 'components-label', label: 'menu.groups.components' },
  {
    id: 'ui-elements',
    label: 'menu.uiElements',
    icon: 'componentDropdown',
    children: [
      { id: 'alerts', label: 'menu.alerts', route: '/ui-elements/alerts' },
      { id: 'badge', label: 'menu.badge', route: '/ui-elements/badge' },
      { id: 'breadcrumb', label: 'menu.breadcrumb', route: '/ui-elements/breadcrumb' },
      { id: 'buttons', label: 'menu.buttons', route: '/ui-elements/buttons' },
      { id: 'icons', label: 'menu.icons', route: '/ui-elements/icons' },
      { id: 'loadings', label: 'menu.loadings', route: '/ui-elements/loadings' },
      { id: 'logo-loading', label: 'menu.logoLoading', route: '/ui-elements/logo-loading' },
      { id: 'button-group', label: 'menu.buttonGroup', route: '/ui-elements/button-group' },
      { id: 'cards', label: 'menu.cards', route: '/ui-elements/cards' },
      { id: 'dropdowns', label: 'menu.dropdowns', route: '/ui-elements/dropdowns' },
      { id: 'images-figures', label: 'menu.imagesFigures', route: '/ui-elements/images-figures' },
      {
        id: 'links-interactions',
        label: 'menu.linksInteractions',
        route: '/ui-elements/links-interactions',
      },
      { id: 'list-group', label: 'menu.listGroup', route: '/ui-elements/list-group' },
      { id: 'navs-tabs', label: 'menu.navsTabs', route: '/ui-elements/navs-tabs' },
      { id: 'object-fit', label: 'menu.objectFit', route: '/ui-elements/object-fit' },
      { id: 'pagination', label: 'menu.pagination', route: '/ui-elements/pagination' },
      { id: 'popovers', label: 'menu.popovers', route: '/ui-elements/popovers' },
      { id: 'progress', label: 'menu.progress', route: '/ui-elements/progress' },
      { id: 'switch', label: 'menu.switch', route: '/ui-elements/switch' },
      { id: 'toasts', label: 'menu.toasts', route: '/ui-elements/toasts' },
      { id: 'tooltips', label: 'menu.tooltips', route: '/ui-elements/tooltips' },
      { id: 'typography', label: 'menu.typography', route: '/ui-elements/typography' },
    ],
  },
  {
    id: 'forms',
    label: 'menu.forms',
    icon: 'form48regular',
    children: [
      {
        id: 'form-elements',
        label: 'menu.formElements',
        icon: 'forms',
        children: [
          {
            id: 'inputs',
            label: 'menu.inputs',
            icon: 'cursorText',
            route: '/forms/form-elements/inputs',
          },
          {
            id: 'checks-radios',
            label: 'menu.checksRadios',
            icon: 'checkbox',
            route: '/forms/form-elements/checks-radios',
          },
          {
            id: 'range',
            label: 'menu.range',
            icon: 'adjustmentsHorizontal',
            route: '/forms/form-elements/range',
          },
          {
            id: 'range-slider',
            label: 'menu.rangeSlider',
            icon: 'arrowsHorizontal',
            route: '/forms/form-elements/range-slider',
          },
          {
            id: 'select',
            label: 'menu.select',
            icon: 'selectDropdown',
            route: '/forms/form-elements/select',
          },
          {
            id: 'file-upload',
            label: 'menu.fileUpload',
            icon: 'fileUpload',
            route: '/forms/form-elements/file-upload',
          },
          {
            id: 'color-picker',
            label: 'menu.colorPicker',
            icon: 'colorPicker',
            route: '/forms/form-elements/color-picker',
          },
        ],
      },
    ],
  },
  {
    id: 'advanced-ui',
    label: 'menu.advancedUi',
    icon: 'party',
    children: [
      { id: 'accordion', label: 'menu.accordion', route: '/advanced-ui/accordion' },
      { id: 'collapse', label: 'menu.collapse', route: '/advanced-ui/collapse' },
      { id: 'carousel', label: 'menu.carousel', route: '/advanced-ui/carousel' },
      { id: 'draggable', label: 'menu.draggable', route: '/advanced-ui/draggable' },
      { id: 'modals', label: 'menu.modals', route: '/advanced-ui/modals' },
      { id: 'drawer', label: 'menu.drawer', route: '/advanced-ui/drawer' },
      { id: 'navbar', label: 'menu.navbar', route: '/advanced-ui/navbar' },
      { id: 'skeleton', label: 'menu.skeleton', route: '/advanced-ui/skeleton' },
      { id: 'rating', label: 'menu.rating', route: '/advanced-ui/rating' },
    ],
  },
  { type: 'label', id: 'maps-icons-label', label: 'menu.groups.mapsIcons' },
  {
    id: 'maps-icons-map',
    label: 'menu.map',
    icon: 'mapOutline',
    children: [
      {
        id: 'google-maps',
        label: 'menu.googleMaps',
        route: '/maps-icons/map/google-maps',
      },
      {
        id: 'leaflet-maps',
        label: 'menu.leafletMaps',
        route: '/maps-icons/map/leaflet-maps',
      },
    ],
  },
  // {
  //   id: 'maps-icons-icons',
  //   label: 'menu.icons',
  //   icon: 'componentDropdown',
  //   disabled: true,
  // },
  { type: 'label', id: 'system-label', label: 'menu.groups.system' },
  {
    id: 'error',
    label: 'menu.error',
    icon: 'exclamationTriangle',
    children: [
      { id: 'error-401', label: 'menu.error401', route: '/error/401' },
      { id: 'error-404', label: 'menu.error404', route: '/error/404' },
      { id: 'error-500', label: 'menu.error500', route: '/error/500' },
    ],
  },
  {
    id: 'utility',
    label: 'menu.utility',
    icon: 'medalLine',
    children: [
      { id: 'avatar', label: 'menu.avatar', route: '/utility/avatar' },
      { id: 'colors', label: 'menu.colors', route: '/utility/colors' },
    ],
  },
  {
    id: 'authentication',
    label: 'menu.authentication',
    icon: 'fingerprint',
    children: [
      {
        id: 'sign-in',
        label: 'menu.signIn',
        icon: 'signIn',
        children: [
          {
            id: 'sign-in-basic',
            label: 'menu.signInBasic',
            icon: 'layoutCentered',
            route: '/auth/sign-in/basic',
          },
          {
            id: 'sign-in-cover',
            label: 'menu.signInCover',
            icon: 'layoutSplit',
            route: '/auth/sign-in/cover',
          },
        ],
      },
      {
        id: 'sign-up',
        label: 'menu.signUp',
        icon: 'signUp',
        children: [
          {
            id: 'sign-up-basic',
            label: 'menu.signUpBasic',
            icon: 'layoutCentered',
            route: '/auth/sign-up/basic',
          },
          {
            id: 'sign-up-cover',
            label: 'menu.signUpCover',
            icon: 'layoutSplit',
            route: '/auth/sign-up/cover',
          },
        ],
      },
      {
        id: 'reset-password',
        label: 'menu.resetPassword',
        icon: 'resetPassword',
        children: [
          {
            id: 'reset-password-basic',
            label: 'menu.resetPasswordBasic',
            icon: 'layoutCentered',
            route: '/auth/reset-password/basic',
          },
          {
            id: 'reset-password-cover',
            label: 'menu.resetPasswordCover',
            icon: 'layoutSplit',
            route: '/auth/reset-password/cover',
          },
        ],
      },
    ],
  },
]
