/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IClarityFullscreen: typeof import('~icons/clarity/fullscreen')['default']
    IClarityLanguageSolid: typeof import('~icons/clarity/language-solid')['default']
    IHugeiconsMenu02: typeof import('~icons/hugeicons/menu02')['default']
    'IIconoir=bellNotification': typeof import('~icons/iconoir/=bell-notification')['default']
    IIconoirBellNotification: typeof import('~icons/iconoir/bell-notification')['default']
    IMaterialSymbolsFullscreen: typeof import('~icons/material-symbols/fullscreen')['default']
    IMaterialSymbolsFullscreenExit: typeof import('~icons/material-symbols/fullscreen-exit')['default']
    IMaterialSymbolsFullscreenExitRounded: typeof import('~icons/material-symbols/fullscreen-exit-rounded')['default']
    IMaterialSymbolsFullscreenRounded: typeof import('~icons/material-symbols/fullscreen-rounded')['default']
    IMaterialSymbolsLightCode: typeof import('~icons/material-symbols-light/code')['default']
    IMaterialSymbolsLightFullscreen: typeof import('~icons/material-symbols-light/fullscreen')['default']
    IMaterialSymbolsLightFullscreenExit: typeof import('~icons/material-symbols-light/fullscreen-exit')['default']
    IMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    IOuiTokenElement: typeof import('~icons/oui/token-element')['default']
    ITablerCode: typeof import('~icons/tabler/code')['default']
    ITablerMoon: typeof import('~icons/tabler/moon')['default']
    ITablerSun: typeof import('~icons/tabler/sun')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
